apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: bitnami/nginx:latest
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: username
      - name: PASSWORD 
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: password 
